#!/usr/bin/env python3
"""Declare the Hebrew and English versions of paired articles to Google.

Run from the repo root:   python3 tools/build_hreflang.py

Only genuine pairs are listed. Most of the articles are not translations of
each other, they are separate pieces on different topics, and inventing an
hreflang pair for them would tell Google something untrue. These three are
real: each covers the same ground in the other language.

x-default points at the English version, which is the sensible fallback for a
reader whose language matches neither.
"""
import re

SITE = 'https://pinkleaf.co.il'

PAIRS = [
    # (english article, hebrew article, what they both cover)
    ('articles/aroid-soil-substrate-israel.html', 'articles/aroid-substrate-diy-mix.html',
     'aroid substrate for Israel: why potting soil fails, the recipe, ratios, pH'),
    ('articles/common-pests-detection-treatment.html', 'articles/pests-diseases-tropical-plants.html',
     'houseplant pests: spider mites, thrips, mealybugs, fungus gnats'),
    ('articles/tc-plant-acclimation.html', 'articles/heb/acclimate-tc-plant.html',
     'acclimating tissue culture plants: tools, the 21 day protocol, common mistakes'),
]

MARK_OPEN = '    <!-- hreflang: generated by tools/build_hreflang.py -->'
MARK_CLOSE = '    <!-- /hreflang -->'


def block(en, he):
    return '\n'.join([
        MARK_OPEN,
        '    <link rel="alternate" hreflang="en" href="%s/%s">' % (SITE, en),
        '    <link rel="alternate" hreflang="he" href="%s/%s">' % (SITE, he),
        '    <link rel="alternate" hreflang="x-default" href="%s/%s">' % (SITE, en),
        MARK_CLOSE,
    ])


LEGACY = re.compile(r'[ \t]*<link rel="alternate" hreflang="[^"]*"[^>]*>\n')


def strip_legacy(path):
    """Remove hreflang tags that sit outside the managed block.

    The site already carried some, and all of them were inert or wrong: three
    Hebrew articles declared a single self-referential hreflang with no other
    version to point at, and one paired a Hebrew article against a page that
    is itself bilingual and never pointed back. Google ignores an hreflang
    that is not reciprocal, so these were costing bytes and nothing else.
    """
    t = open(path, encoding='utf8').read()
    if MARK_OPEN in t:
        start = t.index(MARK_OPEN)
        stop = t.index(MARK_CLOSE) + len(MARK_CLOSE)
        head, managed, tail = t[:start], t[start:stop], t[stop:]
    else:
        head, managed, tail = t, '', ''
    cleaned = LEGACY.sub('', head) + managed + LEGACY.sub('', tail)
    if cleaned != t:
        open(path, 'w', encoding='utf8').write(cleaned)
        return True
    return False


def apply(path, blk):
    t = open(path, encoding='utf8').read()
    if MARK_OPEN in t:
        start = t.index(MARK_OPEN)
        stop = t.index(MARK_CLOSE) + len(MARK_CLOSE)
        t = t[:start] + blk + t[stop:]
    else:
        m = re.search(r'([ \t]*<link rel="canonical"[^>]*>)', t)
        if not m:
            raise SystemExit('no canonical tag to anchor hreflang to in ' + path)
        t = t[:m.end()] + '\n' + blk + t[m.end():]
    open(path, 'w', encoding='utf8').write(t)


if __name__ == '__main__':
    import glob
    stripped = [f for f in sorted(glob.glob('articles/*.html') + glob.glob('articles/heb/*.html'))
                if strip_legacy(f)]
    for f in stripped:
        print('legacy hreflang removed: %s' % f)
    for en, he, topic in PAIRS:
        blk = block(en, he)
        apply(en, blk)
        apply(he, blk)
        print('paired: %s <-> %s' % (en, he))
        print('        %s' % topic)
    print('%d pairs, %d pages updated' % (len(PAIRS), len(PAIRS) * 2))
