#!/usr/bin/env python3
"""Regenerate the Product structured data in index.html from the store itself.

Run from the repo root:   python3 tools/build_product_schema.py

Why this exists: the four hand-written Product blocks drifted away from the
store they sit on. One advertised 199 to 350 shekels for a plant the store
sold at 470, another was marked out of stock while the store had it available.
Google reads that, and so does anyone who clicks a search result.

So the schema is generated from ALL_STORE_ITEMS and ITEM_PRICES, which are the
store's own source of truth. Change a price or a status there, run this, and
the structured data follows. It rewrites only what is between the two marker
comments, so nothing else in index.html is touched.

Products that carry extra hand-written detail keep it through RICH below.
"""
import json, os, re, sys

BEGIN = '<!-- BEGIN PRODUCT SCHEMA (generated by tools/build_product_schema.py; do not hand-edit) -->'
END = '<!-- END PRODUCT SCHEMA -->'
SITE = 'https://pinkleaf.co.il'

# Detail the store data cannot express. Price and availability are never set
# here: those always come from the store, which is the point of this script.
RICH = {
    'PV19': {
        'alternateName': 'אלוקסיה פולי פינק וריאגטה',
        'sku': 'PL-APP-001',
        'description': 'Rare pink-variegated Alocasia with blush-toned leaf markings. Tissue Culture propagated for genetic stability and stable variegation. Each leaf carries a pattern unique to the plant. Acclimated 21 days before shipping.',
        'additionalProperty': [
            {'@type': 'PropertyValue', 'name': 'Propagation', 'value': 'Tissue Culture'},
            {'@type': 'PropertyValue', 'name': 'Acclimation', 'value': '21-day hardening protocol'},
        ],
    },
    'PV81': {
        'alternateName': 'אלוקסיה הארט בלון',
        'description': 'Heart-shaped Alocasia with inflated, balloon-like leaves. Tissue Culture propagated for consistency.',
    },
    'PV25': {
        'alternateName': 'אלוקסיה מקרוריזה וריאגטה',
        'description': 'The Giant Taro in its rare variegated form, with bold white and green sectoral variegation on oversized leaves.',
    },
    'PV48': {
        'alternateName': 'פילודנדרון חוזה בואנו',
        'description': 'Philodendron Jose Buono, large paddle leaves with broad white sectoral variegation.',
    },
}

AVAIL = {
    'available': 'https://schema.org/InStock',
    'coming': 'https://schema.org/PreOrder',
}


def parse_store(html):
    block = html[html.index('const ALL_STORE_ITEMS'):]
    block = block[:block.index('\n        ];')]
    items = []
    for m in re.finditer(
            r'\{\s*id:\s*"([^"]+)",\s*name:\s*"([^"]+)",\s*availability:\s*\[([^\]]*)\][^}]*?status:\s*"(\w+)"',
            block):
        items.append({
            'id': m.group(1),
            'name': m.group(2),
            'grades': re.findall(r'"([^"]+)"', m.group(3)),
            'status': m.group(4),
        })
    pb = html[html.index('const ITEM_PRICES'):]
    pb = pb[:pb.index('\n        };')]
    prices = {m.group(1): int(m.group(2)) for m in re.finditer(r'"([^"]+)":\s*(\d+)', pb)}
    return items, prices


def product(item, prices):
    pid = item['id']
    availability = AVAIL.get(item['status'], AVAIL['coming'])
    offers = []
    for grade in item['grades']:
        price = prices.get('%s_%s' % (pid, grade))
        if price is None:
            continue
        offer = {
            '@type': 'Offer',
            'price': str(price),
            'priceCurrency': 'ILS',
            'availability': availability,
            'url': '%s/#/plant/%s' % (SITE, pid),
            'seller': {'@id': '%s/#store' % SITE},
        }
        # A single unnamed tier reads better than one called "Plant".
        if len(item['grades']) > 1 or grade not in ('Plant',):
            offer['name'] = grade
        offers.append(offer)
    if not offers:
        return None

    node = {
        '@type': 'Product',
        '@id': '%s/#product-%s' % (SITE, pid),
        'name': item['name'],
        'brand': {'@id': '%s/#store' % SITE},
        'category': 'Rare Aroids',
    }
    node.update(RICH.get(pid, {}))
    # Only claim an image when the file is actually there. A Product whose
    # image 404s loses its rich result entirely.
    if os.path.exists('plants/%s.jpg' % pid):
        node['image'] = '%s/plants/%s.jpg' % (SITE, pid)
    node['offers'] = offers[0] if len(offers) == 1 else offers
    return node


def main():
    html = open('index.html', encoding='utf8').read()
    items, prices = parse_store(html)
    nodes = [n for n in (product(i, prices) for i in items) if n]

    lines = [
        BEGIN,
        '    <script type="application/ld+json">',
        '    {"@context":"https://schema.org","@graph":[',
    ]
    body = [json.dumps(n, ensure_ascii=False, separators=(',', ':')) for n in nodes]
    lines += ['      ' + b + (',' if k < len(body) - 1 else '') for k, b in enumerate(body)]
    lines += ['    ]}', '    </script>', END]
    generated = '\n'.join(lines)

    if BEGIN in html:
        start = html.index(BEGIN)
        stop = html.index(END) + len(END)
        html = html[:start] + generated + html[stop:]
    else:
        anchor = '</head>'
        if anchor not in html:
            sys.exit('no </head> to anchor the generated schema to')
        html = html.replace(anchor, generated + '\n' + anchor, 1)

    open('index.html', 'w', encoding='utf8').write(html)
    with_img = sum(1 for n in nodes if 'image' in n)
    in_stock = sum(1 for n in nodes if json.dumps(n).count('InStock'))
    print('products written: %d (%d in stock, %d pre-order)' % (len(nodes), in_stock, len(nodes) - in_stock))
    print('with an image: %d | without: %d' % (with_img, len(nodes) - with_img))
    print('generated block: %.1f KB' % (len(generated) / 1024))


if __name__ == '__main__':
    main()
