#!/usr/bin/env python3
"""Rebuild the lab game's MASTER_DB in index.html from tools/plant-db.csv.

How growth works now:
  1. Drop a new photo into plants/ named by its id, e.g. plants/PV211.jpg
  2. Add one row to tools/plant-db.csv:  PV211,Alocasia Something Variegated,
     (leave the family column blank and it is derived from the first word)
  3. Run:  python3 tools/build_plant_db.py
     The MASTER_DB block in index.html is regenerated between its markers.

Rules, on purpose:
  - A row is only written into the game if it has BOTH a real name AND a photo
    file in plants/. Blank-name rows (photos still waiting on a name) are skipped,
    so the game never shows a made-up or empty plant.
  - family is taken from the CSV if given, otherwise derived: a name starting
    with Alocasia / Monstera / Philodendron maps to that family, everything else
    maps to Others. This matches how the quiz builds its wrong-answer pool.
"""
import csv, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV = os.path.join(ROOT, "tools", "plant-db.csv")
HTML = os.path.join(ROOT, "index.html")
PLANTS = os.path.join(ROOT, "plants")
GENERA = {"alocasia": "Alocasia", "monstera": "Monstera", "philodendron": "Philodendron"}
BEGIN = "// BEGIN MASTER_DB"
END = "// END MASTER_DB"


def derive_family(name, given):
    if given.strip():
        return given.strip()
    return GENERA.get(name.strip().split()[0].lower(), "Others")


def has_photo(pid):
    for ext in ("jpg", "jpeg", "png", "webp"):
        if os.path.exists(os.path.join(PLANTS, pid + "." + ext)):
            return True
    return False


def main():
    rows, skipped_noname, skipped_nophoto = [], 0, 0
    with open(CSV, encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            pid = (r.get("id") or "").strip()
            name = (r.get("name") or "").strip()
            if not pid:
                continue
            if not name:
                skipped_noname += 1
                continue
            if not has_photo(pid):
                skipped_nophoto += 1
                print("  warning: %s has a name but no photo in plants/, skipping" % pid)
                continue
            family = derive_family(name, r.get("family") or "")
            rows.append((pid, name, family))

    rows.sort(key=lambda x: int(re.sub(r"\D", "", x[0]) or 0))

    lines = ["        " + BEGIN + " (auto-generated by tools/build_plant_db.py from tools/plant-db.csv; do not hand-edit between the markers, edit the CSV and regenerate)",
             "        const MASTER_DB = {"]
    for i, (pid, name, family) in enumerate(rows):
        comma = "," if i < len(rows) - 1 else ""
        lines.append('    %s:{"name":%s,"family":%s}%s' % (
            json.dumps(pid), json.dumps(name, ensure_ascii=False),
            json.dumps(family, ensure_ascii=False), comma))
    lines.append("};")
    lines.append("        " + END)
    block = "\n".join(lines)

    html = open(HTML, encoding="utf-8").read()
    pattern = re.compile(r"[ \t]*" + re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pattern.search(html):
        sys.exit("ERROR: MASTER_DB markers not found in index.html")
    html = pattern.sub(lambda _: block, html, count=1)
    open(HTML, "w", encoding="utf-8").write(html)

    print("MASTER_DB rebuilt: %d plants written, %d waiting on a name, %d named-but-no-photo"
          % (len(rows), skipped_noname, skipped_nophoto))


if __name__ == "__main__":
    main()
