/**
 * Pink Leaf Product Catalog
 * To update prices: just change the number next to the plant name.
 * To add a plant: add a new object to the appropriate category array.
 */
const PRODUCTS = [
  // ═══ ALOCASIA (49) ═══
  { id: "azlanii-albo-pink", name: "Azlanii Albo (Pink)", category: "Alocasia", price: 850, image: "" },
  { id: "bambino-aurea", name: "Bambino Aurea", category: "Alocasia", price: 420, image: "" },
  { id: "bambino-pink-lava", name: "Bambino Pink Lava", category: "Alocasia", price: 700, image: "" },
  { id: "black-velvet-pink", name: "Black Velvet Pink", category: "Alocasia", price: 450, image: "" },
  { id: "black-velvet-gold", name: "Black Velvet Gold", category: "Alocasia", price: 450, image: "" },
  { id: "chantrieri-pink", name: "Chantrieri Pink", category: "Alocasia", price: 950, image: "" },
  { id: "cuprea-aurea-latte", name: "Cuprea Aurea Latte", category: "Alocasia", price: 950, image: "" },
  { id: "cuprea-red-secret-mint", name: "Cuprea Red Secret Mint", category: "Alocasia", price: 600, image: "" },
  { id: "cuprea-red-secret-super-pink", name: "Cuprea Red Secret Super Pink", category: "Alocasia", price: 1100, image: "" },
  { id: "cuprea-pink-mint", name: "Cuprea Pink Mint", category: "Alocasia", price: 950, image: "" },
  { id: "cuprea-true-pink", name: "Cuprea True Pink", category: "Alocasia", price: 1500, image: "" },
  { id: "dragon-scale-albo", name: "Dragon Scale Albo", category: "Alocasia", price: 450, image: "" },
  { id: "dragon-scale-tri-color", name: "Dragon Scale Tri-Color", category: "Alocasia", price: 400, image: "" },
  { id: "golden-bone-mint", name: "Golden Bone Mint", category: "Alocasia", price: 700, image: "" },
  { id: "heart-balloon-pink", name: "Heart Balloon Pink", category: "Alocasia", price: 750, image: "" },
  { id: "loco-green", name: "Loco (Green)", category: "Alocasia", price: 120, image: "" },
  { id: "longiloba-thaicon", name: "Longiloba Thaicon", category: "Alocasia", price: 1300, image: "" },
  { id: "maharani-albo", name: "Maharani Albo", category: "Alocasia", price: 700, image: "" },
  { id: "melo-albo", name: "Melo Albo", category: "Alocasia", price: 650, image: "" },
  { id: "metallic-blue-aurea", name: "Metallic Blue Aurea", category: "Alocasia", price: 800, image: "" },
  { id: "metallic-blue-albo", name: "Metallic Blue Albo", category: "Alocasia", price: 900, image: "" },
  { id: "nairobi-nights-a-grade", name: "Nairobi Nights A Grade", category: "Alocasia", price: 650, image: "" },
  { id: "nairobi-nights-camo-tricolor", name: "Nairobi Nights Camouflage Tricolor", category: "Alocasia", price: 650, image: "" },
  { id: "ninja-albo", name: "Ninja Albo", category: "Alocasia", price: 600, image: "" },
  { id: "ninja-pink", name: "Ninja Pink", category: "Alocasia", price: 600, image: "" },
  { id: "nobilis-pink-k", name: "Nobilis Pink K", category: "Alocasia", price: 900, image: "" },
  { id: "pink-dragon-stardust-mint", name: "Pink Dragon Stardust Mint", category: "Alocasia", price: 500, image: "" },
  { id: "polly-ghost-mint", name: "Polly Ghost Mint", category: "Alocasia", price: 450, image: "" },
  { id: "polly-lava", name: "Polly Lava", category: "Alocasia", price: 1000, image: "" },
  { id: "polly-pink", name: "Polly Pink", category: "Alocasia", price: 470, image: "" },
  { id: "pseudo-sanderiana-pink", name: "Pseudo-Sanderiana Pink", category: "Alocasia", price: 650, image: "" },
  { id: "regal-shields-albo", name: "Regal Shields Albo", category: "Alocasia", price: 1300, image: "" },
  { id: "sarian-aurea", name: "Sarian Aurea", category: "Alocasia", price: 600, image: "" },
  { id: "scalprum-mint", name: "Scalprum Mint", category: "Alocasia", price: 600, image: "" },
  { id: "sedenii-aurea", name: "Sedenii Aurea", category: "Alocasia", price: 650, image: "" },
  { id: "silver-dragon-aurea", name: "Silver Dragon Aurea", category: "Alocasia", price: 450, image: "" },
  { id: "simpo-albo", name: "Simpo Albo", category: "Alocasia", price: 450, image: "" },
  { id: "stingray-aurea", name: "Stingray Aurea", category: "Alocasia", price: 500, image: "" },
  { id: "venom-pink-high", name: "Venom Pink (High Variegation)", category: "Alocasia", price: 2000, image: "" },
  { id: "venom-pink-low", name: "Venom Pink (Low Variegation)", category: "Alocasia", price: 1850, image: "" },
  { id: "venom-aurea", name: "Venom Aurea", category: "Alocasia", price: 1800, image: "" },
  { id: "watsoniana-doff-albo", name: "Watsoniana Doff Albo", category: "Alocasia", price: 500, image: "" },
  { id: "watsoniana-doff-pink", name: "Watsoniana Doff Pink", category: "Alocasia", price: 650, image: "" },
  { id: "watsoniana-glossy-pink-shiny", name: "Watsoniana Glossy / Pink Shiny", category: "Alocasia", price: 900, image: "" },
  { id: "wentii-aurea-latte", name: "Wentii Aurea Latte", category: "Alocasia", price: 550, image: "" },
  { id: "wentii-pink", name: "Wentii Pink", category: "Alocasia", price: 550, image: "" },
  { id: "xanthosoma-mickey-mouse", name: "Xanthosoma Mickey Mouse", category: "Alocasia", price: 350, image: "" },
  { id: "yucatan-princess-pink", name: "Yucatan Princess Pink", category: "Alocasia", price: 600, image: "" },
  { id: "zebrina-mint", name: "Zebrina Mint", category: "Alocasia", price: 550, image: "" },

  // ═══ MONSTERA (12) ═══
  { id: "deliciosa-banana-super-golden", name: "Deliciosa Banana Super Golden", category: "Monstera", price: 450, image: "" },
  { id: "devil-monster", name: "Devil Monster", category: "Monstera", price: 1000, image: "" },
  { id: "electro-light", name: "Electro Light", category: "Monstera", price: 550, image: "" },
  { id: "green-snow", name: "Green Snow", category: "Monstera", price: 650, image: "" },
  { id: "legacy", name: "Legacy", category: "Monstera", price: 750, image: "" },
  { id: "lemon-lime-full-variegation", name: "Lemon Lime Full Variegation", category: "Monstera", price: 300, image: "" },
  { id: "lemon-pom-pom", name: "Lemon Pom Pom", category: "Monstera", price: 550, image: "" },
  { id: "mint-full-mint", name: "Mint (Full Mint)", category: "Monstera", price: 250, image: "" },
  { id: "ocean-mint", name: "Ocean Mint", category: "Monstera", price: 1200, image: "" },
  { id: "star-shadow", name: "Star Shadow", category: "Monstera", price: 550, image: "" },
  { id: "white-monster", name: "White Monster", category: "Monstera", price: 250, image: "" },
  { id: "yellow-marilyn", name: "Yellow Marilyn", category: "Monstera", price: 800, image: "" },

  // ═══ PHILODENDRON (11) ═══
  { id: "caramel-marble", name: "Caramel Marble", category: "Philodendron", price: 450, image: "" },
  { id: "green-lemon", name: "Green Lemon", category: "Philodendron", price: 500, image: "" },
  { id: "melano-orange", name: "Melano Orange", category: "Philodendron", price: 450, image: "" },
  { id: "micans", name: "Micans", category: "Philodendron", price: 280, image: "" },
  { id: "narrow", name: "Narrow", category: "Philodendron", price: 280, image: "" },
  { id: "red-congo", name: "Red Congo", category: "Philodendron", price: 120, image: "" },
  { id: "strawberry-marble", name: "Strawberry Marble", category: "Philodendron", price: 400, image: "" },
  { id: "tortum", name: "Tortum", category: "Philodendron", price: 380, image: "" },
  { id: "verrucosum-mint", name: "Verrucosum Mint", category: "Philodendron", price: 450, image: "" },
  { id: "whipple-way", name: "Whipple Way", category: "Philodendron", price: 350, image: "" },
  { id: "white-beauty", name: "White Beauty", category: "Philodendron", price: 1200, image: "" },

  // ═══ OTHER (1) ═══
  { id: "rhaphidophora-tetrasperma-mint", name: "Rhaphidophora Tetrasperma Mint", category: "Other", price: 380, image: "" }
];
